name: findnwalk
description: An app for finding and sharing good places to practice physical activities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_map_marker_popup: ^2.0.1
  flutter_typeahead: ^3.2.1
  geocoding: ^2.0.1
  page_transition: "^2.0.4"
  geolocator: 7.6.2
  flutter_map: ^0.14.0
  anim_search_bar: ^2.0.2
  curved_navigation_bar: ^1.0.1
  latlong2: ^0.8.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  select_form_field: ^2.2.0
  crypto: ^3.0.1
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.2.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_maps_flutter: ^2.1.1


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#3f3f3f"
  image: assets/images/logoWithOutBG.png

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cursor.png
    - assets/images/logoWithOutBG.png
    - assets/images/placeholderPerfilImage.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
